### ISSUE TITLE
ImportError in GRC

### ISSUE THREAD

**Issue by damalingan** [dl1ksv/gr-ax25#11]
Hi! I'm trying to run a simple flowgraph that uses the AX25decode and the Afsk1200 blocks but I keep getting an error:

Traceback (most recent call last):
  File "/home/drue/Desktop/198 files /aprs.py", line 27, in <module>
    import afsk
  File "/usr/local/lib/python2.7/dist-packages/afsk/__init__.py", line 45, in <module>
    from afsk_swig import *
  File "/usr/local/lib/python2.7/dist-packages/afsk/afsk_swig.py", line 28, in <module>
    _afsk_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/afsk/afsk_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_afsk_swig', fp, pathname, description)
ImportError: libgnuradio-afsk-3.7.2.so.0.0.0: cannot open shared object file: No such file or directory

Would really appreciate some suggestions on how to resolve this. Thank you!

**Comment by dl1ksv** [comment]
Try to find out the location of libgnuradio-afsk-3.7.2.so.0.0.0 and add it to your LD_LIBRARY_PATH variable.

**Comment by damalingan** [comment]
Thank you very much
