### ISSUE TITLE
No module named afsk_swig

### ISSUE THREAD

**Issue by archpaladin1** [dl1ksv/gr-ax25#8]
Hello.

It's been a while since this project was worked on, hopefully it is still alive.

I run into the following error when trying to run the APRS.grc example in gnuradio-companion:
```

Traceback (most recent call last):
  File "/home/pmosier/APRS.py", line 23, in <module>
    import afsk
  File "/usr/local/lib/python2.7/dist-packages/afsk/__init__.py", line 45, in <module>
    from afsk_swig import *
ImportError: No module named afsk_swig

```

I followed the build instructions supplied, and it seems true that there is no afsk_swig module anywhere.  Was something supposed to be installed?

I have gnuradio version 3.7.5, installed on Raspbian.

Any help would be appreciated, thanks.
- Paul M

**Comment by archpaladin1** [comment]
Okay nevermind.  I didn't have swig installed during the build process.  So install swig, rebuild, and everything works.

There's already a pull request to add swig to the list of dependencies in the documentation, so if that's done then we should be good.
